### ISSUE TITLE
[Geoserver] temp files not deleted when a WCS getCoverage fails

### ISSUE THREAD

**Issue by Damianofds** [geosolutions-it/evo-odas#70] opened 2017-04-11 09:22 UTC
When a **WCS getCoverage** request fails, the temporary file written in the tomcat temp dir is not properly deleted.

Example:
[This heavy request](http://cloudsdi.geo-solutions.it/geoserver/sentinel2/588/ows?service=WCS&version=2.0.1&request=GetCoverage&coverageId=sentinel2%3Asentinel2-TCI&format=image%2Fgeotiff) returns a 500 error... checking the tomcat tmp directory I found a new file:

```
[ec2-user@ip-10-0-0-43 temp]$ pwd
/var/cache/tomcat7/temp
[ec2-user@ip-10-0-0-43 temp]$ ls -lah | grep tmp
-rw------- 1 tomcat tomcat 3.1G Apr 11 09:20 imageio4559716485413747410.tmp
```

**Comment by aaime** [comment] 2017-04-13 12:34
Cannot reproduce locally, I have to kill and restart GeoServer for the file to be left there, closing the connection in GeoServer face still makes for a removed file.

**Closed** 2017-05-05 14:34 UTC
Labels: bug
