### ISSUE TITLE
[Geoserver] Virtual Services doesn't work with WCS and WMTS services

### ISSUE THREAD

**Issue by Damianofds** [geosolutions-it/evo-odas#72] opened 2017-04-11 09:31 UTC
Virtual Services filtering doesn't work with WCS and WMTS services when adding the layer filter, it works fine when using workspace filter only.

WMS and WFS works fine bot with workspace only and workspace + layername.

**Comment by aaime** [comment] 2017-04-13 12:34
Cannot reproduce yet the WCS issue, works locally, I've added more logging.
For WMTS committed fixes for https://osgeo-org.atlassian.net/projects/GEOS/issues

**Comment by aaime** [comment] 2017-04-14 09:24
Tracked the WCS problem to the current parameter extractor configuration, started a mail thread about it

**Comment by aaime** [comment] 2017-04-21 09:38
Damiano, is this one fixed now?

**Comment by Damianofds** [comment] 2017-04-21 09:42
yes it works, param extractor rules were the problem

**Closed** 2017-04-21 09:43 UTC
Labels: enhancement, in progress
